version: 2
updates:
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: daily
    time: '19:00'
    timezone: Etc/UCT
  pull-request-branch-name:
    separator: '-'
  open-pull-requests-limit: 10
