services:
  gem:
    build: .
    volumes:
      - .:/code
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --save "" --appendonly yes --appendfsync everysec
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data: